# Generated by Django 5.1 on 2024-09-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('rma_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
