# Generated by Django 4.2.7 on 2024-10-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_repairbill_model_number'),
        ('bills', '0004_repairbill_created_at_repairbill_updated_at'),
    ]

    operations = [
    ]
